'use client';

import React, { useCallback } from 'react';
import RiskCard from './RiskCard';
import ScoreGauge from './ScoreGauge';
import ShareableReport from './ShareableReport';

interface Clause {
  title: string;
  summary: string;
  riskLevel: 'green' | 'amber' | 'red';
  recommendation: string;
  suggestedRewrite?: string;
  details?: string;
}

interface GapItem {
  clause: string;
  importance: string;
  suggestion: string;
}

interface AnalysisResult {
  documentType?: string;
  clauses?: Clause[];
  gapAnalysis?: GapItem[];
  overallRisk?: 'low' | 'medium' | 'high';
  fairnessScore?: number;
  _rawOutput?: string;
}

const overallRiskBadge = {
  low: 'bg-green-900/40 text-green-400',
  medium: 'bg-amber-900/40 text-amber-400',
  high: 'bg-red-900/40 text-red-400',
};

const overallRiskLabel = {
  low: 'Low Risk',
  medium: 'Medium Risk',
  high: 'High Risk',
};

const riskOrder: Record<string, number> = { red: 0, amber: 1, green: 2 };

function isValidResult(result: any): result is AnalysisResult {
  return (
    result &&
    typeof result === 'object' &&
    (typeof result.documentType === 'string' || result.documentType === undefined) &&
    (Array.isArray(result.clauses) || result.clauses === undefined) &&
    (Array.isArray(result.gapAnalysis) || result.gapAnalysis === undefined)
  );
}

export default function RiskReport({ result, contractText = '' }: { result: any; contractText?: string }) {
  // ── Download report as JSON ──────────────────────────────────────
  const handleDownload = useCallback(() => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `contractscan-report-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [result]);

  const handleDownloadText = useCallback(() => {
    if (!isValidResult(result)) return;
    const { documentType = 'Unknown', clauses = [], gapAnalysis = [], overallRisk = 'medium', fairnessScore } = result;

    const lines: string[] = [];
    lines.push('═══════════════════════════════════════════');
    lines.push('       CONTRACTSCAN AI — RISK REPORT       ');
    lines.push('═══════════════════════════════════════════');
    lines.push('');
    lines.push(`Document Type: ${documentType}`);
    lines.push(`Overall Risk:  ${overallRiskLabel[overallRisk]}`);
    if (fairnessScore !== undefined) {
      lines.push(`Fairness Score: ${fairnessScore}/100`);
    }
    lines.push('');

    if (clauses.length > 0) {
      lines.push('───────────────────────────────────────────');
      lines.push('  CLAUSE ANALYSIS');
      lines.push('───────────────────────────────────────────');
      clauses.forEach((c, i) => {
        lines.push('');
        lines.push(`  ${i + 1}. ${c.title}  [${c.riskLevel.toUpperCase()}]`);
        lines.push(`     ${c.summary}`);
        lines.push(`     Recommendation: ${c.recommendation}`);
        if (c.suggestedRewrite) {
          lines.push(`     Suggested Rewrite: ${c.suggestedRewrite}`);
        }
      });
    }

    if (gapAnalysis.length > 0) {
      lines.push('');
      lines.push('───────────────────────────────────────────');
      lines.push('  GAP ANALYSIS (Missing Clauses)');
      lines.push('───────────────────────────────────────────');
      gapAnalysis.forEach((g, i) => {
        lines.push('');
        lines.push(`  ${i + 1}. ${g.clause}  [Importance: ${g.importance}]`);
        lines.push(`     ${g.suggestion}`);
      });
    }

    lines.push('');
    lines.push('═══════════════════════════════════════════');
    lines.push('  Generated by ContractScan AI');
    lines.push('  For educational purposes only. Not legal advice.');
    lines.push('═══════════════════════════════════════════');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `contractscan-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [result]);

  // ── Fallback for unexpected data ──────────────────────────────────
  if (!isValidResult(result)) {
    return (
      <div className="w-full max-w-3xl mx-auto p-6">
        <h2 className="text-lg font-bold text-white mb-3">Raw Analysis</h2>
        <pre className="bg-zinc-900/30 border border-zinc-800 rounded-lg p-4 text-xs text-zinc-300 whitespace-pre-wrap overflow-x-auto">
          {JSON.stringify(result, null, 2)}
        </pre>
        <button
          onClick={handleDownload}
          className="mt-4 inline-flex items-center gap-2 rounded-xl bg-zinc-800 px-4 py-2 text-sm font-medium text-zinc-300 hover:bg-zinc-700 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download JSON
        </button>
      </div>
    );
  }

  const {
    documentType = 'Unknown',
    clauses = [],
    gapAnalysis = [],
    overallRisk = 'medium',
    fairnessScore,
  } = result;

  const sortedClauses = [...clauses].sort(
    (a, b) => (riskOrder[a.riskLevel] ?? 3) - (riskOrder[b.riskLevel] ?? 3)
  );

  // ── Stats counts ──────────────────────────────────────────────────
  const redCount = clauses.filter((c) => c.riskLevel === 'red').length;
  const amberCount = clauses.filter((c) => c.riskLevel === 'amber').length;
  const greenCount = clauses.filter((c) => c.riskLevel === 'green').length;
  const gapCount = gapAnalysis.length;

  return (
    <div className="w-full max-w-3xl mx-auto space-y-6">
      {/* ── Header with Score Gauge ──────────────────────────────── */}
      <div className="bg-zinc-900/50 rounded-lg shadow-lg shadow-black/20 border border-zinc-800 p-5">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div className="flex-1 min-w-0">
            <h2 className="text-lg font-bold text-white">Risk Report</h2>
            <p className="text-sm text-zinc-400 mt-0.5">Document type: {documentType}</p>
            <span
              className={`inline-block mt-2 text-xs font-semibold px-3 py-1 rounded-full ${overallRiskBadge[overallRisk]}`}
            >
              {overallRiskLabel[overallRisk]}
            </span>
          </div>

          {/* Score Gauge */}
          {fairnessScore !== undefined && (
            <div className="flex-shrink-0">
              <p className="text-xs text-zinc-500 text-center mb-1 font-medium">Fairness Score</p>
              <ScoreGauge score={fairnessScore} />
            </div>
          )}
        </div>
      </div>

      {/* ── Stats Bar ────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="flex items-center gap-2 rounded-lg bg-red-950/30 border border-red-900/50 px-3 py-2.5">
          <span className="w-3 h-3 rounded-full bg-red-500 flex-shrink-0" />
          <div>
            <p className="text-lg font-bold text-red-400 leading-none">{redCount}</p>
            <p className="text-xs text-red-500 mt-0.5">High Risk</p>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-lg bg-amber-950/30 border border-amber-900/50 px-3 py-2.5">
          <span className="w-3 h-3 rounded-full bg-amber-500 flex-shrink-0" />
          <div>
            <p className="text-lg font-bold text-amber-400 leading-none">{amberCount}</p>
            <p className="text-xs text-amber-500 mt-0.5">Caution</p>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-lg bg-green-950/30 border border-green-900/50 px-3 py-2.5">
          <span className="w-3 h-3 rounded-full bg-green-500 flex-shrink-0" />
          <div>
            <p className="text-lg font-bold text-green-400 leading-none">{greenCount}</p>
            <p className="text-xs text-green-500 mt-0.5">Low Risk</p>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-lg bg-zinc-900/30 border border-zinc-800 px-3 py-2.5">
          <span className="w-3 h-3 rounded-full bg-zinc-500 flex-shrink-0" />
          <div>
            <p className="text-lg font-bold text-zinc-200 leading-none">{gapCount}</p>
            <p className="text-xs text-zinc-400 mt-0.5">Gaps</p>
          </div>
        </div>
      </div>

      {/* ── Clause cards ─────────────────────────────────────────── */}
      {sortedClauses.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-zinc-300 uppercase tracking-wide">Clause Analysis</h3>
          {sortedClauses.map((clause, i) => (
            <RiskCard
              key={i}
              title={clause.title}
              summary={clause.summary}
              riskLevel={clause.riskLevel}
              recommendation={clause.recommendation}
              suggestedRewrite={clause.suggestedRewrite}
              details={clause.details}
            />
          ))}
        </div>
      )}

      {/* ── Gap Analysis ─────────────────────────────────────────── */}
      {gapAnalysis.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-zinc-300 uppercase tracking-wide">Gap Analysis</h3>
          <div className="bg-zinc-900/50 rounded-lg shadow-lg shadow-black/20 border border-zinc-800 p-5 space-y-4">
            {gapAnalysis.map((gap, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="mt-0.5 flex-shrink-0">
                  <svg
                    className="w-5 h-5 text-amber-500"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">{gap.clause}</p>
                  <p className="text-xs text-zinc-400 mt-0.5">
                    <span className="font-medium">Importance:</span> {gap.importance}
                  </p>
                  <p className="text-sm text-zinc-300 mt-1">{gap.suggestion}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Download buttons ─────────────────────────────────────── */}
      <div className="flex flex-wrap items-center gap-3 pt-2">
        <button
          onClick={handleDownloadText}
          className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-black/20 transition-colors hover:bg-blue-700"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download Report
        </button>
        <button
          onClick={handleDownload}
          className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 bg-zinc-800 px-4 py-2.5 text-sm font-medium text-zinc-300 transition-colors hover:bg-zinc-700"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
          </svg>
          Export JSON
        </button>
        <ShareableReport result={result} contractText={contractText} />
      </div>

      {/* ── Empty state ──────────────────────────────────────────── */}
      {sortedClauses.length === 0 && gapAnalysis.length === 0 && (
        <div className="bg-zinc-900/50 rounded-lg shadow-lg shadow-black/20 border border-zinc-800 p-8 text-center">
          <p className="text-zinc-400 text-sm">No analysis data available.</p>
        </div>
      )}
    </div>
  );
}
